// Copyright 2025 TII (SSRC) and the Ghaf contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: evdev/evdev.proto

package evdevproxy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoystickEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Value         int32                  `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoystickEvent) Reset() {
	*x = JoystickEvent{}
	mi := &file_evdev_evdev_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoystickEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoystickEvent) ProtoMessage() {}

func (x *JoystickEvent) ProtoReflect() protoreflect.Message {
	mi := &file_evdev_evdev_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoystickEvent.ProtoReflect.Descriptor instead.
func (*JoystickEvent) Descriptor() ([]byte, []int) {
	return file_evdev_evdev_proto_rawDescGZIP(), []int{0}
}

func (x *JoystickEvent) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *JoystickEvent) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *JoystickEvent) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_evdev_evdev_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_evdev_evdev_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_evdev_evdev_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_evdev_evdev_proto protoreflect.FileDescriptor

const file_evdev_evdev_proto_rawDesc = "" +
	"\n" +
	"\x11evdev/evdev.proto\x12\n" +
	"evdevproxy\"M\n" +
	"\rJoystickEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x05R\x05value\"\x1d\n" +
	"\x03Ack\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2O\n" +
	"\x0fJoystickService\x12<\n" +
	"\fStreamEvents\x12\x19.evdevproxy.JoystickEvent\x1a\x0f.evdevproxy.Ack(\x01B\x1dZ\x1bgivc/modules/api/evdevproxyb\x06proto3"

var (
	file_evdev_evdev_proto_rawDescOnce sync.Once
	file_evdev_evdev_proto_rawDescData []byte
)

func file_evdev_evdev_proto_rawDescGZIP() []byte {
	file_evdev_evdev_proto_rawDescOnce.Do(func() {
		file_evdev_evdev_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_evdev_evdev_proto_rawDesc), len(file_evdev_evdev_proto_rawDesc)))
	})
	return file_evdev_evdev_proto_rawDescData
}

var file_evdev_evdev_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_evdev_evdev_proto_goTypes = []any{
	(*JoystickEvent)(nil), // 0: evdevproxy.JoystickEvent
	(*Ack)(nil),           // 1: evdevproxy.Ack
}
var file_evdev_evdev_proto_depIdxs = []int32{
	0, // 0: evdevproxy.JoystickService.StreamEvents:input_type -> evdevproxy.JoystickEvent
	1, // 1: evdevproxy.JoystickService.StreamEvents:output_type -> evdevproxy.Ack
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_evdev_evdev_proto_init() }
func file_evdev_evdev_proto_init() {
	if File_evdev_evdev_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_evdev_evdev_proto_rawDesc), len(file_evdev_evdev_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_evdev_evdev_proto_goTypes,
		DependencyIndexes: file_evdev_evdev_proto_depIdxs,
		MessageInfos:      file_evdev_evdev_proto_msgTypes,
	}.Build()
	File_evdev_evdev_proto = out.File
	file_evdev_evdev_proto_goTypes = nil
	file_evdev_evdev_proto_depIdxs = nil
}
