// Copyright 2025 TII (SSRC) and the Ghaf contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.4
// source: evdev/evdev.proto

package evdevproxy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JoystickService_StreamEvents_FullMethodName = "/evdevproxy.JoystickService/StreamEvents"
)

// JoystickServiceClient is the client API for JoystickService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JoystickServiceClient interface {
	StreamEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[JoystickEvent, Ack], error)
}

type joystickServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJoystickServiceClient(cc grpc.ClientConnInterface) JoystickServiceClient {
	return &joystickServiceClient{cc}
}

func (c *joystickServiceClient) StreamEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[JoystickEvent, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &JoystickService_ServiceDesc.Streams[0], JoystickService_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[JoystickEvent, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type JoystickService_StreamEventsClient = grpc.ClientStreamingClient[JoystickEvent, Ack]

// JoystickServiceServer is the server API for JoystickService service.
// All implementations must embed UnimplementedJoystickServiceServer
// for forward compatibility.
type JoystickServiceServer interface {
	StreamEvents(grpc.ClientStreamingServer[JoystickEvent, Ack]) error
	mustEmbedUnimplementedJoystickServiceServer()
}

// UnimplementedJoystickServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJoystickServiceServer struct{}

func (UnimplementedJoystickServiceServer) StreamEvents(grpc.ClientStreamingServer[JoystickEvent, Ack]) error {
	return status.Errorf(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedJoystickServiceServer) mustEmbedUnimplementedJoystickServiceServer() {}
func (UnimplementedJoystickServiceServer) testEmbeddedByValue()                         {}

// UnsafeJoystickServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JoystickServiceServer will
// result in compilation errors.
type UnsafeJoystickServiceServer interface {
	mustEmbedUnimplementedJoystickServiceServer()
}

func RegisterJoystickServiceServer(s grpc.ServiceRegistrar, srv JoystickServiceServer) {
	// If the following call pancis, it indicates UnimplementedJoystickServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JoystickService_ServiceDesc, srv)
}

func _JoystickService_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(JoystickServiceServer).StreamEvents(&grpc.GenericServerStream[JoystickEvent, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type JoystickService_StreamEventsServer = grpc.ClientStreamingServer[JoystickEvent, Ack]

// JoystickService_ServiceDesc is the grpc.ServiceDesc for JoystickService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JoystickService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "evdevproxy.JoystickService",
	HandlerType: (*JoystickServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _JoystickService_StreamEvents_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "evdev/evdev.proto",
}
